module.exports = {
    BAT_HEIGHT: 100,
    BAT_WIDTH: 15,
    BAT_H_SPACE: 100,
    BAT_V_SPACE: 30,
    COMP_SPEED: 6,
    CANVAS_HEIGHT: 600,
    CANVAS_WIDTH: 800,
    DIGIT_CELL_SIZE: 10,
    PLAYER_SCORE_X: 150,
    PLAYER_SCORE_Y: 50,
    COMPUTER_SCORE_X: 500,
    COMPUTER_SCORE_Y: 50,
    SCORE_SPACE:10

}